version: '3.3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    ports:
      - "5432:5432"
    healthcheck:
      test: "/etc/init.d/postgresql status"
      timeout: 1s
      retries: 60
    restart: unless-stopped
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
#      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
       - ./docker/db/data:/var/lib/postgresql/data:rw
  ###< doctrine/doctrine-bundle ###
  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/trip_builder
    links:
      - database
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/trip_builder
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  yarn:
    build: ./docker/yarn
    user: "${HOST_UID:-1000}:${HOST_GROUP_ID:-1000}"
    volumes:
      - ./:/home/node/app
      - ~/.ssh:/home/node/.ssh

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
