controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    controller: App\Controller\IndexController::index
    path: /
    methods: [ GET ]

api_platform:
    resource: .
    type: api_platform
    prefix: /api
